### ISSUE TITLE
Special AI Mobs not respecting Chunk protection

### ISSUE THREAD

**Issue by Divineaspect** [FatherToast/SpecialAI#20]
https://github.com/mcenderdragon/Futurepack-API/issues/839#issuecomment-1001047017

**Comment by FatherToast** [comment]
I'm not sure how this actually pertains to SAI - what is chunk protection?  This mod does not cause mobs to do anything that vanilla mobs can't already do in terms of chunks/blocks and does follow the mob griefing game rule.

**Comment by mcenderdragon** [comment]
@FatherToast I am lsitening to BLockEvents, and it seems like you arent firing them notably (BlockEvent.BreakEvent, BlockEvent.EntityPlaceEvent, aswell as bucket fill & explosions events) but I think tjust the block place & break events are the most important since that will ensure mod compatibility.

**Comment by FatherToast** [comment]
I am firing LivingDestroyBlockEvent (along with a few others) to test if blocks can be broken.  BlockEvent.BreakEvent is fired for players only, so it won't catch mobs trying to break blocks.

**Comment by mcenderdragon** [comment]
LivingDestroyBlockEvent  is not part of the BLockEvents ?

**Comment by FatherToast** [comment]
No, it is a subclass of the LivingEvent and in vanilla it is used for the wither, ender dragon, and zombies to check if they are allowed to break blocks/doors.  I suspect if you are not checking this event, these vanilla mobs will be able to break blocks in protected chunks as well.
